apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF4TWpreApORFV3TUROYUZ3MDBNekF4TWpreE5EVXdNRE5hTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEQm9DaXhKOFpuYjNlWTZYejV2YWZhOVRPMCtSNHorRHZQOVFKbFVvMUZPRkFuaDE3YQpzSnlDL2kxdlQ0SHpCSnFoalYvZzJnU0VlSkJPWXpaOG5vRVAzYnpVc29sREkyUGtmeTZBTklORnNuVlZ5ZWRlCjhoMThaVnVreEtCQXJqUmp3QVExNFZoTEZ1bW4wZE55WnpMamVFQzFTZWhZVUxRWFlkTklLU1dFQ2ZLbmk3L0MKb0RkMEg0b3NIZlVyMDJXUm9CamlqbElsVkorYm9iREtnWG8rR0tJaWRrNGJHY0V0dklWRHZwQitTeUdsUHpnMQptS3Y4Z0plb0FsY1dLeU1ORndUMFFjUE1vaHBzc0dzelREbTY0VlB5bXQ2K3F4Ry9BN0l0dWF1SkIwcXlmSlc0CnRNMGYzRHlCZFhQa3FRUTA1bWdwUXc2MFVlTkhQZk9UT2ZCdkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNubHpFRWtYTGZ6Y09uTUljUApyR1d1bGR5Tm1UQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFkU3pSMDZTZWU0czMyWnBMZEVvaE54V09FSXQ4CmNMMXM1bVl0SEJpUUVKT2lsQ1gxZGxBQWRPM21meW1DN05CMjBBNlBoWGFZWHlpNE9zQU1xOXE0Mk16Ujdad3IKbDhkQkZGMGhmNFl6dElIL1ZZelk5STlPUitrQzNNK1kzUkxRVS9Fd1QwVE1adUk0U2Q0cDFFcG9sd3JRLzB0bgovdjVkZ1lOS0ozNFFteEprU3hMOWppQkF6dmM4ZTNLeFBMQU9pY0JSNG5HcndpNVJINUREQWVOOW5zV2lrNDd6CmwzY1IvRmR6YVoxR3lJbEVob21LSEMzYUFRK01jenQxS0ZYNFFrR2RMaVBDTnRRVVVOUWxzT1BYbEhkV3YwdzEKRCtFY0hOcE1VSGpjL2RzYXhHNE4wM1dTeW5EUFZEMkViaVV3c1kxS3JySWdQS1FwemxoZ0JxZGNRUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://5ae11b97-6eb5-4a4a-9b43-c043c11a2e7a.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_9fbb821bce8d224638d808fedd2caef383a3eb3c0850b8cb4471d2778010cc84
